# Generated by Django 5.2.11 on 2026-02-27 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('album', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='photo',
            old_name='image_url',
            new_name='public_url',
        ),
        migrations.RemoveField(
            model_name='photo',
            name='owner',
        ),
        migrations.AddField(
            model_name='photo',
            name='storage_path',
            field=models.CharField(default='temp', max_length=300),
            preserve_default=False,
        ),
    ]
