# Generated by Django 5.2.11 on 2026-04-17 07:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('album', '0003_photo_owner'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='photo',
            name='public_url',
        ),
        migrations.RemoveField(
            model_name='photo',
            name='storage_path',
        ),
        migrations.AddField(
            model_name='photo',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='photos/'),
        ),
    ]
